### ISSUE TITLE
Kiwi colour sheme 

### ISSUE THREAD

**Issue by tmelliott** [G-Thomson/Manu#3]
![kiwi](https://resources.stuff.co.nz/content/dam/images/1/x/b/n/v/q/image.related.StuffLandscapeThreeByTwo.1151x768.1xblgi.png/1570648988403.jpg)

**Comment by G-Thomson** [comment]
Hi Tom

Do you have a use case for the Kiwi palette? 
I originally avoided it as it would just be several shades of brown, but I could add it if you like.

Where is the image sourced from?

**Comment by tmelliott** [comment]
No, but I feel like birds of NZ is incomplete without our boring lil mascot. Image is just randomly from Google (https://resources.stuff.co.nz/content/dam/images/1/x/b/n/v/q/image.related.StuffLandscapeThreeByTwo.1151x768.1xblgi.png/1570648988403.jpg). It'll probably be too brown though... a few comical use-cases though :D 

You've done an amazing job with the rest, btw - hope you're doing well in not-NZ!

**Comment by G-Thomson** [comment]
Thanks! I'm doing well!

I'll add in the Kiwi when I have a spare moment.

**Comment by G-Thomson** [comment]
I have finally added a Kiwi colour palette. Surprisingly a lot of pink tones in the feathers.

**Comment by tmelliott** [comment]
Amazing work @G-Thomson :heart_eyes:
