### ISSUE TITLE
Installation failure on docker containers

### ISSUE THREAD

**Issue by tayaza** [G-Thomson/Manu#4]
Hi Geoffrey,

Thank you for building this cool tool. Works fine on my laptop but I can't get to install it on an RStudio docker container. The error is:
`Error: Failed to install 'unknown package' from GitHub: HTTP error 404. No commit found for the ref master Did you spell the repo owner (`G-Thomson`) and repo name (`Manu`) correctly? - If spelling is correct, check that you have the required permissions to access the repo.`
docker container: rocker/tidyverse4.0.1
devtools version: 2.3.2.9000 (from `devtools::install_github("hadley/devtools")`)
RStudio has read + write permissions on the mounted volume.

Do you have a quick way of fixing this?

Thank you.

**Comment by G-Thomson** [comment]
Hi Tayza

At the end of last year Github changed the name of the default branches of repositories from "master" to "main". Thus old versions of `devtools` look for a master branch which doesn't exist.

I think you can use this to specify you want the "main" branch using:
`devtools::install_github("G-Thomson/Manu@main")`
or
`devtools::install_github("G-Thomson/Manu", ref = "HEAD")`

Also, I believe the repository for `devtools` which is actively developed is [https://github.com/r-lib/devtools](https://github.com/r-lib/devtools), but the version on CRAN should be sufficiently up to date.

**Comment by tayaza** [comment]
Hi Geoffrey,

Thanks for the reply. I was able to install it on rocker/tidyverse:4.0.3 so all good. Closing this.
