### ISSUE TITLE
Download Github Failed 

### ISSUE THREAD

**Issue by andresxmv** [G-Thomson/Manu#5]
Hi! I I have trouble download your pretty color palette

I run this:
`devtools::install_github("G-Thomson/Manu")`

and the output is this:

`Downloading GitHub repo G-Thomson/Manu@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/G-Thomson/Manu/tarball/HEAD' failed`

Thanks a lot!

**Comment by G-Thomson** [comment]
Hi

Try updating devtools `install.packages("devtools")` and remotes `install.packages("remotes")` before trying to install it again.

**Comment by andresxmv** [comment]
Hi! I try but the same error :(

devtools: 2.4.1
remotes: 2.4.0

**Comment by G-Thomson** [comment]
It works for me with devtools 2.4.2. Try upgrading to that.

**Comment by andresxmv** [comment]
Thanks!

**Comment by Svega750** [comment]
None of this works.
